theme: jekyll-theme-minimal
title: Jose Armando Aguasvivas Manzano
description: PhD candidate in Cognitive Neuroscience
site_url: https://github.com/JoseAAManzano/joseaamanzano.github.io/
logo: img/logo.jpg
